---
- hosts: localhost
  connection: local 
  gather_facts: no
  tasks:
    - name: Build an image and push it to a private repo
      docker_image:
        build:
          path: .
        name: rtaran20singh/myapp
        tag: v1
        push: yes
        source: build